package info;

import java.util.ArrayList;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;


public class army {

	public ArrayList<armyinfo> list() {
		ArrayList<armyinfo> list = new ArrayList<armyinfo>();
		String jsonInfo = "{\r\n" + "	\"DESCRIPTION\": {\r\n" + "		\"rowno\": \"행번호\",\r\n"
				+ "		\"kind\": \"종목\",\r\n" + "		\"dvs\": \"구분\",\r\n" + "		\"sex\": \"성별\",\r\n"
				+ "		\"age_lwlmtprcdc\": \"연령 하한선\",\r\n" + "		\"age_uprlmtprcdc\": \"연령 상한선\",\r\n"
				+ "		\"grd\": \"등급\",\r\n" + "		\"std_lwlmtprcdc\": \"기준 하한선\",\r\n"
				+ "		\"std_uprlmtprcdc\": \"기준 상한선\"\r\n" + "	},\r\n" + "	\"DATA\": [\r\n" + "		{\r\n"
				+ "			\"rowno\": \"1\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"72\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"2\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"64\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"71\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"3\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"56\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"63\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"4\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"48\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"55\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"5\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"47\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"6\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"7\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"70\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"8\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"62\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"69\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"9\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"54\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"61\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"10\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"46\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"53\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"11\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"45\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"12\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"13\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"68\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"14\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"60\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"67\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"15\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"52\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"59\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"16\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"44\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"51\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"17\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"43\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"18\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"19\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"65\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"20\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"57\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"64\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"21\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"49\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"56\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"22\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"41\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"48\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"23\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"40\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"24\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"25\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"61\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"26\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"53\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"60\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"27\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"45\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"52\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"28\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"37\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"44\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"29\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"36\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"30\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"31\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"57\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"32\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"49\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"56\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"33\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"41\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"48\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"34\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"33\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"40\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"35\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"32\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"36\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"37\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"54\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"38\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"46\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"53\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"39\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"38\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"45\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"40\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"30\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"37\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"41\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"29\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"42\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"43\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"51\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"44\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"43\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"50\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"45\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"35\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"42\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"46\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"27\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"34\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"47\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"26\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"48\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"49\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"49\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"50\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"41\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"48\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"51\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"33\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"40\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"52\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"25\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"32\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"53\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"24\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"54\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"55\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"47\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"56\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"39\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"46\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"57\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"31\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"38\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"58\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"23\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"30\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"59\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"22\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"60\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"61\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"44\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"62\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"36\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"43\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"63\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"28\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"35\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"64\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"20\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"27\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"65\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"19\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"66\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"67\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"42\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"68\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"34\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"41\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"69\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"26\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"33\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"70\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"18\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"25\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"71\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"17\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"72\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"73\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"40\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"74\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"32\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"39\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"75\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"24\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"31\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"76\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"16\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"23\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"77\",\r\n" + "			\"kind\": \"팔굽혀펴기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"15\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"78\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"79\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"86\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"80\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"78\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"85\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"81\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"70\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"77\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"82\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"62\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"69\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"83\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"61\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"84\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"85\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"84\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"86\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"76\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"83\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"87\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"68\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"75\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"88\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"60\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"67\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"89\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"59\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"90\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"91\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"80\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"92\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"72\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"79\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"93\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"65\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"71\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"94\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"57\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"64\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"95\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"56\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"96\",\r\n" + "			\"kind\": \"\",\r\n" + "			\"dvs\": \"\",\r\n"
				+ "			\"sex\": \"\",\r\n" + "			\"age_lwlmtprcdc\": \"\",\r\n"
				+ "			\"age_uprlmtprcdc\": \"\",\r\n" + "			\"grd\": \"\",\r\n"
				+ "			\"std_lwlmtprcdc\": \"\",\r\n" + "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n"
				+ "		{\r\n" + "			\"rowno\": \"97\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"76\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"98\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"68\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"75\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"99\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"60\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"67\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"100\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"52\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"59\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"101\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"51\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"102\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"103\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"72\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"104\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"64\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"71\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"105\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"56\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"63\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"106\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"48\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"55\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"107\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"47\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"108\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"109\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"68\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"110\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"60\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"67\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"111\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"52\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"59\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"112\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"44\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"51\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"113\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"43\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"114\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"115\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"65\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"116\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"57\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"64\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"117\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"49\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"56\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"118\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"41\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"48\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"119\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"40\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"120\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"121\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"62\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"122\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"54\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"61\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"123\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"46\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"53\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"124\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"38\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"45\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"125\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"37\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"126\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"127\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"60\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"128\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"52\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"59\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"129\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"44\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"51\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"130\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"36\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"43\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"131\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"35\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"132\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"133\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"58\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"134\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"50\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"57\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"135\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"42\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"49\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"136\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"34\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"41\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"137\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"33\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"138\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"139\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"56\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"140\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"48\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"55\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"141\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"40\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"47\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"142\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"32\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"39\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"143\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"31\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"144\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"145\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"54\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"146\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"46\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"53\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"147\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"38\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"45\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"148\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"30\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"37\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"149\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"29\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"150\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"151\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"52\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"999\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"152\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"44\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"51\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"153\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"36\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"43\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"154\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"28\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"35\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"155\",\r\n" + "			\"kind\": \"윗몸일으키기(2분)\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"0\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"27\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"156\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"157\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"12:30\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"00:01\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"158\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"12:31\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"13:32\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"159\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"13:33\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"14:34\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"160\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"14:35\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"15:36\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"161\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"0\",\r\n" + "			\"age_uprlmtprcdc\": \"25\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"15:37\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"180:00\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"162\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"163\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"12:45\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"00:01\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"164\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"12:46\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"13:52\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"165\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"13:53\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"14:59\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"166\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"15:00\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"16:06\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"167\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"26\",\r\n" + "			\"age_uprlmtprcdc\": \"30\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"16:07\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"180:00\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"168\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"169\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"13:00\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"00:01\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"170\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"13:01\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"14:12\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"171\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"14:13\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"15:24\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"172\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"15:25\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"16:36\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"173\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"31\",\r\n" + "			\"age_uprlmtprcdc\": \"35\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"16:37\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"180:00\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"174\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"175\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"13:15\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"00:01\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"176\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"13:16\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"14:32\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"177\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"14:33\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"15:49\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"178\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"15:50\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"17:06\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"179\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"36\",\r\n" + "			\"age_uprlmtprcdc\": \"40\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"17:07\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"180:00\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"180\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"181\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"13:30\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"00:01\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"182\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"13:31\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"14:49\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"183\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"14:50\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"16:07\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"184\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"16:08\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"17:26\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"185\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"41\",\r\n" + "			\"age_uprlmtprcdc\": \"43\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"17:27\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"180:00\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"186\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"187\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"13:45\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"00:01\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"188\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"13:46\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"15:05\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"189\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"15:06\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"16:26\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"190\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"16:27\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"17:46\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"191\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"44\",\r\n" + "			\"age_uprlmtprcdc\": \"46\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"17:47\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"180:00\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"192\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"193\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"14:00\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"00:01\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"194\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"14:01\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"15:25\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"195\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"15:26\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"16:51\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"196\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"16:52\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"18:16\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"197\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"47\",\r\n" + "			\"age_uprlmtprcdc\": \"49\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"18:17\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"180:00\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"198\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"199\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"14:15\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"00:01\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"200\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"14:16\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"15:42\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"201\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"15:43\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"17:09\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"202\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"17:10\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"18:36\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"203\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"50\",\r\n" + "			\"age_uprlmtprcdc\": \"51\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"18:36\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"180:00\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"204\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"205\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"14:30\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"00:01\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"206\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"14:31\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"16:02\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"207\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"16:03\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"17:34\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"208\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"17:35\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"19:06\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"209\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"52\",\r\n" + "			\"age_uprlmtprcdc\": \"53\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"19:07\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"180:00\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"210\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"211\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"14:45\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"00:01\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"212\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"14:46\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"16:19\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"213\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"16:20\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"17:52\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"214\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"17:53\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"19:26\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"215\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"54\",\r\n" + "			\"age_uprlmtprcdc\": \"55\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"19:27\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"180:00\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"216\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"217\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"15:10\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"00:01\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"218\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"15:11\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"16:46\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"219\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"16:47\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"18:23\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"220\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"18:24\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"19:59\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"221\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"56\",\r\n" + "			\"age_uprlmtprcdc\": \"57\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"20:00\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"180:00\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"222\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"223\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"15:35\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"00:01\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"224\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"15:36\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"17:13\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"225\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"17:14\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"18:51\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"226\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"18:52\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"20:29\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"227\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"58\",\r\n" + "			\"age_uprlmtprcdc\": \"59\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"20:30\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"180:00\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"228\",\r\n" + "			\"kind\": \"\",\r\n"
				+ "			\"dvs\": \"\",\r\n" + "			\"sex\": \"\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"\",\r\n" + "			\"age_uprlmtprcdc\": \"\",\r\n"
				+ "			\"grd\": \"\",\r\n" + "			\"std_lwlmtprcdc\": \"\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"229\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"특급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"16:00\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"00:01\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"230\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"1급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"16:01\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"17:40\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"231\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"2급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"17:41\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"19:19\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"232\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"3급(합격)\",\r\n" + "			\"std_lwlmtprcdc\": \"19:20\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"20:59\"\r\n" + "		},\r\n" + "		{\r\n"
				+ "			\"rowno\": \"233\",\r\n" + "			\"kind\": \"3Km달리기\",\r\n"
				+ "			\"dvs\": \"군인\",\r\n" + "			\"sex\": \"남성\",\r\n"
				+ "			\"age_lwlmtprcdc\": \"60\",\r\n" + "			\"age_uprlmtprcdc\": \"99\",\r\n"
				+ "			\"grd\": \"불합격\",\r\n" + "			\"std_lwlmtprcdc\": \"21:00\",\r\n"
				+ "			\"std_uprlmtprcdc\": \"180:00\"\r\n" + "		}\r\n" + "	]\r\n" + "}";
		
			
			try {
				JSONParser parser = new JSONParser();
				JSONObject object = (JSONObject) parser.parse(jsonInfo);
				JSONArray arr = (JSONArray) object.get("DATA");
				for (int i = 0; i < arr.size(); i++) {
					JSONObject obj = (JSONObject) arr.get(i);
					armyinfo info = new armyinfo();
					info.setKind((String)obj.get("kind"));
					info.setSex((String)obj.get("sex"));
					info.setAge_lwlmtprcdc((String)obj.get("age_lwlmtprcdc") +  "세 ~ " + (String)obj.get("age_uprlmtprcdc") + "세");
					info.setAge_uprlmtprcdc((String)obj.get("age_uprlmtprcdc"));
					info.setStd_lwlmtprcdc((String)obj.get("std_lwlmtprcdc"));
					info.setStd_uprlmtprcdc((String)obj.get("std_uprlmtprcdc"));
					info.setGrd((String)obj.get("grd"));
					list.add(info);
				}
			} catch (Exception e) {
				e.printStackTrace();
			}

		
		return list;
	}
	
}
